import type {
  ConnectOptions,
  PeerLocator,
  PrincipalMatcher,
} from "@arduano/p2prpc-core";

/**
 * Reachability and identity are intentionally separate: a signed ticket is a
 * locator, while endpointId is trusted bootstrap configuration.
 */
export interface PinnedPeerTarget {
  readonly endpointId: string;
  readonly locator: PeerLocator;
}
/** Exact shared-secret principal generated by p2prpc for an Iroh endpoint. */
export function endpointPrincipal(endpointId: string): PrincipalMatcher {
  return Object.freeze({
    id: endpointId,
    subject: endpointId,
    issuer: null,
    clientId: null,
    tenantId: null,
  });
}

/** Build a dial target that pins both transport and application identity. */
export function pinnedConnectOptions(target: PinnedPeerTarget): ConnectOptions {
  return Object.freeze({
    expectedPeerId: target.endpointId,
    expectedPrincipal: endpointPrincipal(target.endpointId),
    locator: snapshotLocator(target.locator),
  });
}

function snapshotLocator(locator: PeerLocator): PeerLocator {
  switch (locator.kind) {
    case "ticket":
      return Object.freeze({ kind: "ticket", ticket: locator.ticket });
    case "dns":
      return Object.freeze({ kind: "dns" });
    case "mdns":
      return Object.freeze({
        kind: "mdns",
        ...(locator.serviceName !== undefined
          ? { serviceName: locator.serviceName }
          : {}),
      });
  }
}
